name: DIU final result fetch
on: 
#  schedule: # Run workflow automatically
#   - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  diu_result_fetch:
    name: Auto fetch
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Run check
      run: |
        pip install requests
        python - <<END
        import requests, sys
        def check():
          for workflow in requests.get("https://api.github.com/repos/biplobsd/miscActionScripts/actions/workflows/17051643/runs").json()['workflow_runs'][1:]:
            if workflow['status'] == 'in_progress':
              print("Already runing in another workflow job")
              sys.exit(1)
            else:
              print(f"{workflow['run_number']} is not running job")
        for _ in range(3):
          try:
            check()
            break
          except KeyError:
            continue
        END
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -r requirements.txt
    - name: Run script
      run: cd diu/result/;python3 getResultList.py
    
    - name: Commit files 
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update results"
        git pull --rebase
    - name: Push changes 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}    
    
    
